#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Custom repo checks (empty files/folders)
node scripts/pre-commit-checks.js || exit 1

# TypeScript project-wide type check
pnpm -s type-check || exit 1

# Lint only changed files
pnpm -s lint-staged || exit 1
